- "#PowerToWomen":
  - text: "We believe that laws change for the better, when women hold the pen. Through leadership development, campaign support, and policy advocacy, we place women at the heart of legislative power."
  - cta: "Donate to our Fundraising"
  - link: "https://fundraising.babylon19.org"
- "#WeTheVoices":
  - text: "An expressive space for collective truth-telling. Explore campaigns, media and community-led storystelling from the front-lines. Democracy thrives when we speak up!<!--A civic platform for speaking truth to power. Add your voice to current issues, critique parliamentary bills, or share your story. Democracy thrives when we're loud.<!--An expressive space for collective truth-telling. Here, marginalized identities speak back to systems through testimonies, media and more.<!--A digital megaphone for marginalized voices. Explore campaigns, media and community-led storystelling from the front-lines.-->"
  - cta: "Join the Dialogues"
  - link: "https://wethevoices.babylon19.org"
- "#ChapterShe":
  - text: "A feminist book club and cadet program. We believe the first chapter of any story, or any activist's journey, can lead to legends. Read, rise, and write the future."
  - cta: "Start your Adventure"
  - link: "https://chaptershe.babylon19.org"